[2020-09-06-19:26:51]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F7D808>
[2020-09-06-19:32:38]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F7DF48>
[2020-09-06-19:43:59]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find'<traceback object at 0x111C7328>
[2020-09-06-20:01:37]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x138B9C28>
[2020-09-06-20:02:38]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x0127DE48>
[2020-09-06-20:03:38]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x012741A8>
[2020-09-06-20:04:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x11193FE8>
[2020-09-06-20:05:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x011D1828>
[2020-09-06-20:06:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x111933C8>
[2020-09-06-20:07:41]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x110DF608>
[2020-09-06-20:08:42]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x01275068>
[2020-09-06-20:09:43]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x138C3468>
[2020-09-06-20:10:44]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x10FA0D08>
[2020-09-06-20:11:45]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x1168E7A8>
[2020-09-06-20:42:04]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x11029EE8>
[2020-09-06-21:15:59]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x11129388>
[2020-09-06-21:22:33]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x02D96728>
[2020-09-06-22:37:42]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x138BF648>
[2020-09-06-22:50:02]from le360 : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x1131D8E8>
[2020-09-06-22:50:32]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F42228>
[2020-09-06-23:07:04]from le360 : <class 'AttributeError'>'NoneType' object has no attribute 'find'<traceback object at 0x011F55A8>
[2020-09-07-09:14:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571118>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:15:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74DE8>
[2020-09-07-09:16:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x115710E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:17:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x115712F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74C68>
[2020-09-07-09:18:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571598>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:19:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74A08>
[2020-09-07-09:20:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571508>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:55:09]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03E360E8>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))<traceback object at 0x02BDBEC8>
[2020-09-07-10:04:35]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10EBE310>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))<traceback object at 0x02B015E8>
[2020-09-07-12:53:35]from leseco : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='leseco.ma', port=443): Max retries exceeded with url: /resultats-saham-assurance-confirme-limpact-negatif-de-la-covid-19/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x014AE520>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))<traceback object at 0x031F2248>
[2020-09-07-16:01:58]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x11BD1688>
[2020-09-07-16:02:59]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x11F38D28>
[2020-09-07-16:04:03]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x00F2AC68>
[2020-09-07-16:05:06]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x11E73968>
[2020-09-07-16:06:09]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01822EA8>
[2020-09-07-16:07:11]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01877368>
[2020-09-07-16:08:13]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x11EE1148>
[2020-09-07-16:09:14]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01AA67C8>
[2020-09-07-16:10:18]from leseco : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='leseco.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x009AC048>
[2020-09-07-16:10:25]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x0EE9B528>
[2020-09-07-16:11:28]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01919688>
[2020-09-07-16:12:31]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01917568>
[2020-09-07-16:15:21]from le360 : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x033CAA28>
[2020-09-07-17:37:37]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11520B68>
[2020-09-07-18:06:04]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x1372BF68>
